### PR TITLE
Replace 'makePathRelative' with 'basePath' - #109

### PR DESCRIPTION
**Pull request by revyh**
The continuation of #109 

@faergeek @stevelacy check out my tests, I'm not so sure about it.

### CODE REVIEW

**Comment by stevelacy** [comment]
Thanks, can you make sure to use 2space tabs?

**Comment by revyh** [comment]
I was confused about indentation, because some files uses spaces, some tabs, some mixes both. So I decided to use spaces because 'index.js' uses them. If you want tabs, I can amend spaces only in my commit or leave it as is and make another PR with tabs in all sources.

**Comment by stevelacy** [comment]
All files are supposed to use 2 spaces as a tab, not tabs. I noticed the very deep indentation here: https://github.com/stevelacy/gulp-stylus/pull/145/files#diff-e5b8495db5b34b144973178386ba5ceeR219 which is why I mentioned it.
I can fix it later

**Comment by stevelacy** [comment]
merged, thanks!

**Comment by revyh** [comment]
Oh, my inattention :confused:. Thx for the plugin.

**Pull request merged**
