### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Benew**
Fix missing space before headline

### CODE REVIEW

**Comment by jenius** [comment]
could you merge these two commits?

**Comment by Benew** [comment]
Well I cannot. Can't you?

**Comment by stevelacy** [comment]
@Benew `git squash` http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by Benew** [comment]
I thought you wanted me to merge it into your master. Squash done!

**Comment by stevelacy** [comment]
Thanks!

**Pull request merged**
