### PR TITLE
Sourcemap Support

### LINKED ISSUE #70: Support for gulp-sourcemaps
... would be great.
https://github.com/floridoo/gulp-sourcemaps

### PR DESCRIPTION
**Pull request by jenius**
Self-explanatory. This has been a long time coming.

Closes #70

### CODE REVIEW

**Comment by jenius** [comment]
Ok this is ready to roll, implemented and tested. The file contents come back completely clean with no source mapping url comment junk, and the sourcemap comes back as `file.sourceMap` with accurate source references and `sourcesContent` embedded as well. I assume gulp sourcemap tooling takes care of the rest (writing the sourcemap, deciding whether to inline it, etc).

Last thing I'm going to add here is some docs in the readme, should be ready for merge though. I also removed the previous hacky inline sourcemaps test because this is a much better way to do it, in accordance with how sourcemaps are supposed to work in gulp.

**Comment by jenius** [comment]
Ok 100% ready to merge. If you approve @stevelacy merge away. There is a test in place, and I also updated and ran the `examples` folder, and they work perfectly, both inline and external. :tada: :tada: :tada:

**Comment by stevelacy** [comment]
:tada: :tada: :+1: 

Just a thought, if there is a file.sourceMap coming in from `gulp-sourcemaps` should we set `sourcemaps: true` by default?
Just bringing it up as [gulp-less](https://github.com/plus3network/gulp-less/blob/master/index.js#L36)
and [gulp-coffee](https://github.com/wearefractal/gulp-coffee/blob/master/index.js#L27) do it.

**Comment by jenius** [comment]
Sure, if the other ones do it. Honestly I feel like that should be up to the user and is out of scope for this plugin, but it doesn't seem like it would do any harm, so if you want to and the other ones do it, why not :grinning:

**Comment by contra** [comment]
Hmm I'm getting some weird behavior when using plugins. I'm using nib, jeet, and autoprefixer plugins 

```coffee-script
    .pipe sourcemaps.init()
      .pipe stylus
        use: [
          nib(),
          jeet(),
          autoprefixer(
            cascade: true
            browsers: cssSupport
          )
        ]
      .pipe concat 'index.css'
    .pipe sourcemaps.write '.'
```

The file names and line numbers are coming up totally incorrect

**Comment by contra** [comment]
For example,

```stylus
@require 'nib'
@require 'jeet'

.index-component
  align()
```

in client/components/Index/index.styl comes up with .index-component linking to client/index.styl line 12

**Comment by contra** [comment]
It's a nib issue, nib uses stylus 0.45 which does not support sourcemaps. I'm not even going to bother opening an issue since nib is where progress goes to die https://github.com/tj/nib/pulls https://github.com/tj/nib/issues

You might want to document that nib doesn't support sourcemaps so people don't open issues thinking that it's the plugin somehow

**Comment by jenius** [comment]
@contra give [axis](https://github.com/jenius/axis) a shot. It builds on top of nib but is actually maintained and documented. If you can still produce issues with axis, I'm willing to put a bunch of work into making sure that all issues are cleared up, even if that means forking nib and depending on that. We use axis heavily across a number of sites and rely heavily on it.

**Comment by stevelacy** [comment]
I'll pull out all doc and example support for nib in gulp-stylus with v2 onwards.

**Comment by contra** [comment]
Sent a PR to fix this in nib, should be getting merged soon. Seems like autoprefixer-stylus was also a problem, switching to gulp-autoprefixer fixed it. May also want to document that

**Pull request merged**
