### PR TITLE
use the encoding option passed in

### PR DESCRIPTION
**Pull request by eddiemonge**
encoding from through was not being passed. Not sure if that was intentional or not

### CODE REVIEW

**Comment by stevelacy** [comment]
Can you merge all your PR's?

**Comment by eddiemonge** [comment]
I was trying to make it easier to merge the individual pieces. Easier to merge small chunks and also easier to bisect when there are problems. If you really want me to though, I can.

**Comment by jenius** [comment]
:+1: lgtm

**Comment by stevelacy** [comment]
Thanks for the PR's :smile:

**Pull request merged**
