### PR TITLE
Updated version of dependency accord to one that no longer uses fobje…

### PR DESCRIPTION
**Pull request by robertdbailey**
…ct, which is licensed solely under GPLv3.

### CODE REVIEW

**Comment by stevelacy** [comment]
Build failed?

**Comment by stevelacy** [comment]
Here it is, the required function `Object.assign` does not exist before node v4 in accord.

**Comment by stevelacy** [comment]
Thanks! Let me know if there's any GPL in other dependencies

**Comment by robertdbailey** [comment]
Awesome, thanks for moving on this so fast!  There were no other dependencies with stated GPL sub-dependencies.  cheers

**Pull request merged**
