### PR TITLE
exposed native stylus module

### PR DESCRIPTION
**Pull request by JoshuaWise**
It's frequent to need the original `stylus` module in gulpfiles, but annoying to install both `stylus` and `gulp-stylus`.
Therefore, I've exposed the `stylus` module within `gulp-stylus`.

### CODE REVIEW

**Comment by stevelacy** [comment]
@jenius thoughts?
Looks good to me, probably minor version update. I'll add docs to the readme for it.

**Comment by jenius** [comment]
Yeah I can get down with this. Docs, rebase, and merge up!

**Comment by stevelacy** [comment]
@JoshuaWise Please add documentation to the readme to explain the changes, then I'll merge

**Comment by JoshuaWise** [comment]
Three months later, I add the documentation! Hurray!

**Comment by stevelacy** [comment]
End of year PRs :smile: 
merged, published to 2.2.0

**Comment by jenius** [comment]
:tada:

**Pull request merged**
